[project]
name = "faster-whisper-large-v3-turbo-ct2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faster-whisper>=1.1.1",
    "mlx-whisper>=0.4.2",
    "tqdm>=4.67.1",
    "yt-dlp>=2024.0.0",
]
